### ISSUE TITLE
ISerializer?

### ISSUE THREAD

**Issue by HX-Rd** [SOLIDSoftworks/Solid.Http#37]
Just an idea, was writing an extension and found my self wanting to get a hold of the serializers but with the current implementation this is not possible, since we implement the serialization explicitly in the With...Content methods. I think it would be useful to have a interface like so ( just brainstorming here )
```csharp
    public interface ISerializer
    {
        bool CanSerialize(string mimeType);
        Task<Stream> SerializeAsync<T>(T obj);
    }
```
And then register ISerializers in the service container like we do with the deserializers. Just an idea, what do you think?

**Comment by gislikonrad** [comment]
I'm wondering how this would actually work. Right now, in the json feature for example, there is an extension method called **AddJsonContent** which serialized the content and sets the mime type. To me, that is the serializer. How would this ISerializer work? Would we have a method called AddSerializedContent? How would it know what to serialize to? Would you have to set the mime type first, because that needs to be on the HttpContent object.
